version: "3.9"
services:

  jenkins-blueocean:
    build: 
      context: ../docker
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins/home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    deploy:
      mode: global
  
  dind:
    image: docker:dind
    privileged: true
    ports:
      - "2376:2376"
    networks:
      - jenkins
    volumes:
     - run:/var/run
     - jenkins-docker-certs:/certs/client
     - jenkins-data:/var/jenkins/home
    environment:
     - DOCKER_TLS_CERTDIR=/certs
    deploy:
      mode: global

volumes:

  jenkins-data:
  jenkins-docker-certs:
  run:

networks:

  jenkins:
